// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secondary_meta.proto

package com.Proto;

public final class SecondaryMetaClass {
  private SecondaryMetaClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SecondaryMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SecondaryMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string video_summary = 1;</code>
     */
    java.lang.String getVideoSummary();
    /**
     * <code>optional string video_summary = 1;</code>
     */
    com.google.protobuf.ByteString
        getVideoSummaryBytes();

    /**
     * <code>optional int64 block_info = 2;</code>
     */
    long getBlockInfo();

    /**
     * <code>optional string container_info = 3;</code>
     */
    java.lang.String getContainerInfo();
    /**
     * <code>optional string container_info = 3;</code>
     */
    com.google.protobuf.ByteString
        getContainerInfoBytes();

    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <code>optional string encode_info = 5;</code>
     */
    java.lang.String getEncodeInfo();
    /**
     * <code>optional string encode_info = 5;</code>
     */
    com.google.protobuf.ByteString
        getEncodeInfoBytes();

    /**
     * <code>optional int64 frame_number = 6;</code>
     */
    long getFrameNumber();

    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    java.util.List<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup>
        getFrameMetaInfoList();
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup getFrameMetaInfo(int index);
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    int getFrameMetaInfoCount();
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    java.util.List<? extends com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder>
        getFrameMetaInfoOrBuilderList();
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder getFrameMetaInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SecondaryMeta}
   */
  public  static final class SecondaryMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SecondaryMeta)
      SecondaryMetaOrBuilder {
    // Use SecondaryMeta.newBuilder() to construct.
    private SecondaryMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SecondaryMeta() {
      videoSummary_ = "";
      blockInfo_ = 0L;
      containerInfo_ = "";
      timestamp_ = 0L;
      encodeInfo_ = "";
      frameNumber_ = 0L;
      frameMetaInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SecondaryMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              videoSummary_ = s;
              break;
            }
            case 16: {

              blockInfo_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              containerInfo_ = s;
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              encodeInfo_ = s;
              break;
            }
            case 48: {

              frameNumber_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                frameMetaInfo_ = new java.util.ArrayList<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup>();
                mutable_bitField0_ |= 0x00000040;
              }
              frameMetaInfo_.add(
                  input.readMessage(com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          frameMetaInfo_ = java.util.Collections.unmodifiableList(frameMetaInfo_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.Proto.SecondaryMetaClass.SecondaryMeta.class, com.Proto.SecondaryMetaClass.SecondaryMeta.Builder.class);
    }

    public interface FrameInfoGroupOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SecondaryMeta.FrameInfoGroup)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int64 start_index = 1;</code>
       */
      long getStartIndex();

      /**
       * <code>optional int64 start_frame_no = 2;</code>
       */
      long getStartFrameNo();
    }
    /**
     * Protobuf type {@code SecondaryMeta.FrameInfoGroup}
     */
    public  static final class FrameInfoGroup extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:SecondaryMeta.FrameInfoGroup)
        FrameInfoGroupOrBuilder {
      // Use FrameInfoGroup.newBuilder() to construct.
      private FrameInfoGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private FrameInfoGroup() {
        startIndex_ = 0L;
        startFrameNo_ = 0L;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private FrameInfoGroup(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                startIndex_ = input.readInt64();
                break;
              }
              case 16: {

                startFrameNo_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_FrameInfoGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_FrameInfoGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.class, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder.class);
      }

      public static final int START_INDEX_FIELD_NUMBER = 1;
      private long startIndex_;
      /**
       * <code>optional int64 start_index = 1;</code>
       */
      public long getStartIndex() {
        return startIndex_;
      }

      public static final int START_FRAME_NO_FIELD_NUMBER = 2;
      private long startFrameNo_;
      /**
       * <code>optional int64 start_frame_no = 2;</code>
       */
      public long getStartFrameNo() {
        return startFrameNo_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (startIndex_ != 0L) {
          output.writeInt64(1, startIndex_);
        }
        if (startFrameNo_ != 0L) {
          output.writeInt64(2, startFrameNo_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (startIndex_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, startIndex_);
        }
        if (startFrameNo_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, startFrameNo_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup)) {
          return super.equals(obj);
        }
        com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup other = (com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup) obj;

        boolean result = true;
        result = result && (getStartIndex()
            == other.getStartIndex());
        result = result && (getStartFrameNo()
            == other.getStartFrameNo());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + START_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartIndex());
        hash = (37 * hash) + START_FRAME_NO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartFrameNo());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SecondaryMeta.FrameInfoGroup}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SecondaryMeta.FrameInfoGroup)
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_FrameInfoGroup_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_FrameInfoGroup_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.class, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder.class);
        }

        // Construct using com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          startIndex_ = 0L;

          startFrameNo_ = 0L;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_FrameInfoGroup_descriptor;
        }

        public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup getDefaultInstanceForType() {
          return com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.getDefaultInstance();
        }

        public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup build() {
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup buildPartial() {
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup result = new com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup(this);
          result.startIndex_ = startIndex_;
          result.startFrameNo_ = startFrameNo_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup) {
            return mergeFrom((com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup other) {
          if (other == com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.getDefaultInstance()) return this;
          if (other.getStartIndex() != 0L) {
            setStartIndex(other.getStartIndex());
          }
          if (other.getStartFrameNo() != 0L) {
            setStartFrameNo(other.getStartFrameNo());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long startIndex_ ;
        /**
         * <code>optional int64 start_index = 1;</code>
         */
        public long getStartIndex() {
          return startIndex_;
        }
        /**
         * <code>optional int64 start_index = 1;</code>
         */
        public Builder setStartIndex(long value) {
          
          startIndex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 start_index = 1;</code>
         */
        public Builder clearStartIndex() {
          
          startIndex_ = 0L;
          onChanged();
          return this;
        }

        private long startFrameNo_ ;
        /**
         * <code>optional int64 start_frame_no = 2;</code>
         */
        public long getStartFrameNo() {
          return startFrameNo_;
        }
        /**
         * <code>optional int64 start_frame_no = 2;</code>
         */
        public Builder setStartFrameNo(long value) {
          
          startFrameNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 start_frame_no = 2;</code>
         */
        public Builder clearStartFrameNo() {
          
          startFrameNo_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:SecondaryMeta.FrameInfoGroup)
      }

      // @@protoc_insertion_point(class_scope:SecondaryMeta.FrameInfoGroup)
      private static final com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup();
      }

      public static com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<FrameInfoGroup>
          PARSER = new com.google.protobuf.AbstractParser<FrameInfoGroup>() {
        public FrameInfoGroup parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new FrameInfoGroup(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<FrameInfoGroup> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<FrameInfoGroup> getParserForType() {
        return PARSER;
      }

      public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int VIDEO_SUMMARY_FIELD_NUMBER = 1;
    private volatile java.lang.Object videoSummary_;
    /**
     * <code>optional string video_summary = 1;</code>
     */
    public java.lang.String getVideoSummary() {
      java.lang.Object ref = videoSummary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        videoSummary_ = s;
        return s;
      }
    }
    /**
     * <code>optional string video_summary = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVideoSummaryBytes() {
      java.lang.Object ref = videoSummary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoSummary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCK_INFO_FIELD_NUMBER = 2;
    private long blockInfo_;
    /**
     * <code>optional int64 block_info = 2;</code>
     */
    public long getBlockInfo() {
      return blockInfo_;
    }

    public static final int CONTAINER_INFO_FIELD_NUMBER = 3;
    private volatile java.lang.Object containerInfo_;
    /**
     * <code>optional string container_info = 3;</code>
     */
    public java.lang.String getContainerInfo() {
      java.lang.Object ref = containerInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        containerInfo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string container_info = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContainerInfoBytes() {
      java.lang.Object ref = containerInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int ENCODE_INFO_FIELD_NUMBER = 5;
    private volatile java.lang.Object encodeInfo_;
    /**
     * <code>optional string encode_info = 5;</code>
     */
    public java.lang.String getEncodeInfo() {
      java.lang.Object ref = encodeInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encodeInfo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string encode_info = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEncodeInfoBytes() {
      java.lang.Object ref = encodeInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encodeInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRAME_NUMBER_FIELD_NUMBER = 6;
    private long frameNumber_;
    /**
     * <code>optional int64 frame_number = 6;</code>
     */
    public long getFrameNumber() {
      return frameNumber_;
    }

    public static final int FRAME_META_INFO_FIELD_NUMBER = 7;
    private java.util.List<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup> frameMetaInfo_;
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    public java.util.List<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup> getFrameMetaInfoList() {
      return frameMetaInfo_;
    }
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    public java.util.List<? extends com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder>
        getFrameMetaInfoOrBuilderList() {
      return frameMetaInfo_;
    }
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    public int getFrameMetaInfoCount() {
      return frameMetaInfo_.size();
    }
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup getFrameMetaInfo(int index) {
      return frameMetaInfo_.get(index);
    }
    /**
     * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
     */
    public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder getFrameMetaInfoOrBuilder(
        int index) {
      return frameMetaInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVideoSummaryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, videoSummary_);
      }
      if (blockInfo_ != 0L) {
        output.writeInt64(2, blockInfo_);
      }
      if (!getContainerInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, containerInfo_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      if (!getEncodeInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, encodeInfo_);
      }
      if (frameNumber_ != 0L) {
        output.writeInt64(6, frameNumber_);
      }
      for (int i = 0; i < frameMetaInfo_.size(); i++) {
        output.writeMessage(7, frameMetaInfo_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVideoSummaryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, videoSummary_);
      }
      if (blockInfo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, blockInfo_);
      }
      if (!getContainerInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, containerInfo_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (!getEncodeInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, encodeInfo_);
      }
      if (frameNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, frameNumber_);
      }
      for (int i = 0; i < frameMetaInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, frameMetaInfo_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.Proto.SecondaryMetaClass.SecondaryMeta)) {
        return super.equals(obj);
      }
      com.Proto.SecondaryMetaClass.SecondaryMeta other = (com.Proto.SecondaryMetaClass.SecondaryMeta) obj;

      boolean result = true;
      result = result && getVideoSummary()
          .equals(other.getVideoSummary());
      result = result && (getBlockInfo()
          == other.getBlockInfo());
      result = result && getContainerInfo()
          .equals(other.getContainerInfo());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getEncodeInfo()
          .equals(other.getEncodeInfo());
      result = result && (getFrameNumber()
          == other.getFrameNumber());
      result = result && getFrameMetaInfoList()
          .equals(other.getFrameMetaInfoList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + VIDEO_SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getVideoSummary().hashCode();
      hash = (37 * hash) + BLOCK_INFO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockInfo());
      hash = (37 * hash) + CONTAINER_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getContainerInfo().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + ENCODE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getEncodeInfo().hashCode();
      hash = (37 * hash) + FRAME_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrameNumber());
      if (getFrameMetaInfoCount() > 0) {
        hash = (37 * hash) + FRAME_META_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getFrameMetaInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.Proto.SecondaryMetaClass.SecondaryMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.Proto.SecondaryMetaClass.SecondaryMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SecondaryMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SecondaryMeta)
        com.Proto.SecondaryMetaClass.SecondaryMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.Proto.SecondaryMetaClass.SecondaryMeta.class, com.Proto.SecondaryMetaClass.SecondaryMeta.Builder.class);
      }

      // Construct using com.Proto.SecondaryMetaClass.SecondaryMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFrameMetaInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        videoSummary_ = "";

        blockInfo_ = 0L;

        containerInfo_ = "";

        timestamp_ = 0L;

        encodeInfo_ = "";

        frameNumber_ = 0L;

        if (frameMetaInfoBuilder_ == null) {
          frameMetaInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          frameMetaInfoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.Proto.SecondaryMetaClass.internal_static_SecondaryMeta_descriptor;
      }

      public com.Proto.SecondaryMetaClass.SecondaryMeta getDefaultInstanceForType() {
        return com.Proto.SecondaryMetaClass.SecondaryMeta.getDefaultInstance();
      }

      public com.Proto.SecondaryMetaClass.SecondaryMeta build() {
        com.Proto.SecondaryMetaClass.SecondaryMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.Proto.SecondaryMetaClass.SecondaryMeta buildPartial() {
        com.Proto.SecondaryMetaClass.SecondaryMeta result = new com.Proto.SecondaryMetaClass.SecondaryMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.videoSummary_ = videoSummary_;
        result.blockInfo_ = blockInfo_;
        result.containerInfo_ = containerInfo_;
        result.timestamp_ = timestamp_;
        result.encodeInfo_ = encodeInfo_;
        result.frameNumber_ = frameNumber_;
        if (frameMetaInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            frameMetaInfo_ = java.util.Collections.unmodifiableList(frameMetaInfo_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.frameMetaInfo_ = frameMetaInfo_;
        } else {
          result.frameMetaInfo_ = frameMetaInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.Proto.SecondaryMetaClass.SecondaryMeta) {
          return mergeFrom((com.Proto.SecondaryMetaClass.SecondaryMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.Proto.SecondaryMetaClass.SecondaryMeta other) {
        if (other == com.Proto.SecondaryMetaClass.SecondaryMeta.getDefaultInstance()) return this;
        if (!other.getVideoSummary().isEmpty()) {
          videoSummary_ = other.videoSummary_;
          onChanged();
        }
        if (other.getBlockInfo() != 0L) {
          setBlockInfo(other.getBlockInfo());
        }
        if (!other.getContainerInfo().isEmpty()) {
          containerInfo_ = other.containerInfo_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getEncodeInfo().isEmpty()) {
          encodeInfo_ = other.encodeInfo_;
          onChanged();
        }
        if (other.getFrameNumber() != 0L) {
          setFrameNumber(other.getFrameNumber());
        }
        if (frameMetaInfoBuilder_ == null) {
          if (!other.frameMetaInfo_.isEmpty()) {
            if (frameMetaInfo_.isEmpty()) {
              frameMetaInfo_ = other.frameMetaInfo_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureFrameMetaInfoIsMutable();
              frameMetaInfo_.addAll(other.frameMetaInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.frameMetaInfo_.isEmpty()) {
            if (frameMetaInfoBuilder_.isEmpty()) {
              frameMetaInfoBuilder_.dispose();
              frameMetaInfoBuilder_ = null;
              frameMetaInfo_ = other.frameMetaInfo_;
              bitField0_ = (bitField0_ & ~0x00000040);
              frameMetaInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFrameMetaInfoFieldBuilder() : null;
            } else {
              frameMetaInfoBuilder_.addAllMessages(other.frameMetaInfo_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.Proto.SecondaryMetaClass.SecondaryMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.Proto.SecondaryMetaClass.SecondaryMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object videoSummary_ = "";
      /**
       * <code>optional string video_summary = 1;</code>
       */
      public java.lang.String getVideoSummary() {
        java.lang.Object ref = videoSummary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          videoSummary_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string video_summary = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVideoSummaryBytes() {
        java.lang.Object ref = videoSummary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoSummary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string video_summary = 1;</code>
       */
      public Builder setVideoSummary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        videoSummary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string video_summary = 1;</code>
       */
      public Builder clearVideoSummary() {
        
        videoSummary_ = getDefaultInstance().getVideoSummary();
        onChanged();
        return this;
      }
      /**
       * <code>optional string video_summary = 1;</code>
       */
      public Builder setVideoSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        videoSummary_ = value;
        onChanged();
        return this;
      }

      private long blockInfo_ ;
      /**
       * <code>optional int64 block_info = 2;</code>
       */
      public long getBlockInfo() {
        return blockInfo_;
      }
      /**
       * <code>optional int64 block_info = 2;</code>
       */
      public Builder setBlockInfo(long value) {
        
        blockInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 block_info = 2;</code>
       */
      public Builder clearBlockInfo() {
        
        blockInfo_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object containerInfo_ = "";
      /**
       * <code>optional string container_info = 3;</code>
       */
      public java.lang.String getContainerInfo() {
        java.lang.Object ref = containerInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          containerInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string container_info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContainerInfoBytes() {
        java.lang.Object ref = containerInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          containerInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string container_info = 3;</code>
       */
      public Builder setContainerInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        containerInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string container_info = 3;</code>
       */
      public Builder clearContainerInfo() {
        
        containerInfo_ = getDefaultInstance().getContainerInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string container_info = 3;</code>
       */
      public Builder setContainerInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        containerInfo_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object encodeInfo_ = "";
      /**
       * <code>optional string encode_info = 5;</code>
       */
      public java.lang.String getEncodeInfo() {
        java.lang.Object ref = encodeInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          encodeInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string encode_info = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEncodeInfoBytes() {
        java.lang.Object ref = encodeInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encodeInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string encode_info = 5;</code>
       */
      public Builder setEncodeInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encodeInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string encode_info = 5;</code>
       */
      public Builder clearEncodeInfo() {
        
        encodeInfo_ = getDefaultInstance().getEncodeInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string encode_info = 5;</code>
       */
      public Builder setEncodeInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        encodeInfo_ = value;
        onChanged();
        return this;
      }

      private long frameNumber_ ;
      /**
       * <code>optional int64 frame_number = 6;</code>
       */
      public long getFrameNumber() {
        return frameNumber_;
      }
      /**
       * <code>optional int64 frame_number = 6;</code>
       */
      public Builder setFrameNumber(long value) {
        
        frameNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 frame_number = 6;</code>
       */
      public Builder clearFrameNumber() {
        
        frameNumber_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup> frameMetaInfo_ =
        java.util.Collections.emptyList();
      private void ensureFrameMetaInfoIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          frameMetaInfo_ = new java.util.ArrayList<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup>(frameMetaInfo_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder> frameMetaInfoBuilder_;

      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public java.util.List<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup> getFrameMetaInfoList() {
        if (frameMetaInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(frameMetaInfo_);
        } else {
          return frameMetaInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public int getFrameMetaInfoCount() {
        if (frameMetaInfoBuilder_ == null) {
          return frameMetaInfo_.size();
        } else {
          return frameMetaInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup getFrameMetaInfo(int index) {
        if (frameMetaInfoBuilder_ == null) {
          return frameMetaInfo_.get(index);
        } else {
          return frameMetaInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder setFrameMetaInfo(
          int index, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup value) {
        if (frameMetaInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.set(index, value);
          onChanged();
        } else {
          frameMetaInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder setFrameMetaInfo(
          int index, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder builderForValue) {
        if (frameMetaInfoBuilder_ == null) {
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          frameMetaInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder addFrameMetaInfo(com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup value) {
        if (frameMetaInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.add(value);
          onChanged();
        } else {
          frameMetaInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder addFrameMetaInfo(
          int index, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup value) {
        if (frameMetaInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.add(index, value);
          onChanged();
        } else {
          frameMetaInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder addFrameMetaInfo(
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder builderForValue) {
        if (frameMetaInfoBuilder_ == null) {
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.add(builderForValue.build());
          onChanged();
        } else {
          frameMetaInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder addFrameMetaInfo(
          int index, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder builderForValue) {
        if (frameMetaInfoBuilder_ == null) {
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          frameMetaInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder addAllFrameMetaInfo(
          java.lang.Iterable<? extends com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup> values) {
        if (frameMetaInfoBuilder_ == null) {
          ensureFrameMetaInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, frameMetaInfo_);
          onChanged();
        } else {
          frameMetaInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder clearFrameMetaInfo() {
        if (frameMetaInfoBuilder_ == null) {
          frameMetaInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          frameMetaInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public Builder removeFrameMetaInfo(int index) {
        if (frameMetaInfoBuilder_ == null) {
          ensureFrameMetaInfoIsMutable();
          frameMetaInfo_.remove(index);
          onChanged();
        } else {
          frameMetaInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder getFrameMetaInfoBuilder(
          int index) {
        return getFrameMetaInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder getFrameMetaInfoOrBuilder(
          int index) {
        if (frameMetaInfoBuilder_ == null) {
          return frameMetaInfo_.get(index);  } else {
          return frameMetaInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public java.util.List<? extends com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder>
           getFrameMetaInfoOrBuilderList() {
        if (frameMetaInfoBuilder_ != null) {
          return frameMetaInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(frameMetaInfo_);
        }
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder addFrameMetaInfoBuilder() {
        return getFrameMetaInfoFieldBuilder().addBuilder(
            com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.getDefaultInstance());
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder addFrameMetaInfoBuilder(
          int index) {
        return getFrameMetaInfoFieldBuilder().addBuilder(
            index, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.getDefaultInstance());
      }
      /**
       * <code>repeated .SecondaryMeta.FrameInfoGroup frame_meta_info = 7;</code>
       */
      public java.util.List<com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder>
           getFrameMetaInfoBuilderList() {
        return getFrameMetaInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder>
          getFrameMetaInfoFieldBuilder() {
        if (frameMetaInfoBuilder_ == null) {
          frameMetaInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroup.Builder, com.Proto.SecondaryMetaClass.SecondaryMeta.FrameInfoGroupOrBuilder>(
                  frameMetaInfo_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          frameMetaInfo_ = null;
        }
        return frameMetaInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SecondaryMeta)
    }

    // @@protoc_insertion_point(class_scope:SecondaryMeta)
    private static final com.Proto.SecondaryMetaClass.SecondaryMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.Proto.SecondaryMetaClass.SecondaryMeta();
    }

    public static com.Proto.SecondaryMetaClass.SecondaryMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SecondaryMeta>
        PARSER = new com.google.protobuf.AbstractParser<SecondaryMeta>() {
      public SecondaryMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SecondaryMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SecondaryMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SecondaryMeta> getParserForType() {
      return PARSER;
    }

    public com.Proto.SecondaryMetaClass.SecondaryMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SecondaryMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SecondaryMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SecondaryMeta_FrameInfoGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SecondaryMeta_FrameInfoGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024secondary_meta.proto\"\207\002\n\rSecondaryMeta" +
      "\022\025\n\rvideo_summary\030\001 \001(\t\022\022\n\nblock_info\030\002 " +
      "\001(\003\022\026\n\016container_info\030\003 \001(\t\022\021\n\ttimestamp" +
      "\030\004 \001(\003\022\023\n\013encode_info\030\005 \001(\t\022\024\n\014frame_num" +
      "ber\030\006 \001(\003\0226\n\017frame_meta_info\030\007 \003(\0132\035.Sec" +
      "ondaryMeta.FrameInfoGroup\032=\n\016FrameInfoGr" +
      "oup\022\023\n\013start_index\030\001 \001(\003\022\026\n\016start_frame_" +
      "no\030\002 \001(\003B\"\n\014com.protobufB\022SecondaryMetaC" +
      "lassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SecondaryMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SecondaryMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SecondaryMeta_descriptor,
        new java.lang.String[] { "VideoSummary", "BlockInfo", "ContainerInfo", "Timestamp", "EncodeInfo", "FrameNumber", "FrameMetaInfo", });
    internal_static_SecondaryMeta_FrameInfoGroup_descriptor =
      internal_static_SecondaryMeta_descriptor.getNestedTypes().get(0);
    internal_static_SecondaryMeta_FrameInfoGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SecondaryMeta_FrameInfoGroup_descriptor,
        new java.lang.String[] { "StartIndex", "StartFrameNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
