// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_sequence_file.proto

package com.Proto;

public final class VideoSequenceFileRecordClass {
  private VideoSequenceFileRecordClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoSequenceFileRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VideoSequenceFileRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 start_frame = 1;</code>
     */
    long getStartFrame();

    /**
     * <code>optional int64 start_index = 2;</code>
     */
    long getStartIndex();

    /**
     * <code>optional int64 end_frame = 3;</code>
     */
    long getEndFrame();

    /**
     * <code>optional int64 end_index = 4;</code>
     */
    long getEndIndex();

    /**
     * <code>optional int64 record_frame_number = 5;</code>
     */
    long getRecordFrameNumber();

    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    java.util.List<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData> 
        getRecordVideoDataList();
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData getRecordVideoData(int index);
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    int getRecordVideoDataCount();
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    java.util.List<? extends com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder> 
        getRecordVideoDataOrBuilderList();
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder getRecordVideoDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code VideoSequenceFileRecord}
   */
  public  static final class VideoSequenceFileRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VideoSequenceFileRecord)
      VideoSequenceFileRecordOrBuilder {
    // Use VideoSequenceFileRecord.newBuilder() to construct.
    private VideoSequenceFileRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoSequenceFileRecord() {
      startFrame_ = 0L;
      startIndex_ = 0L;
      endFrame_ = 0L;
      endIndex_ = 0L;
      recordFrameNumber_ = 0L;
      recordVideoData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VideoSequenceFileRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              startFrame_ = input.readInt64();
              break;
            }
            case 16: {

              startIndex_ = input.readInt64();
              break;
            }
            case 24: {

              endFrame_ = input.readInt64();
              break;
            }
            case 32: {

              endIndex_ = input.readInt64();
              break;
            }
            case 40: {

              recordFrameNumber_ = input.readInt64();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                recordVideoData_ = new java.util.ArrayList<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData>();
                mutable_bitField0_ |= 0x00000020;
              }
              recordVideoData_.add(
                  input.readMessage(com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          recordVideoData_ = java.util.Collections.unmodifiableList(recordVideoData_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.class, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.Builder.class);
    }

    public interface VideoDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:VideoSequenceFileRecord.VideoData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int64 frameNo = 1;</code>
       */
      long getFrameNo();

      /**
       * <code>optional bytes frameData = 2;</code>
       */
      com.google.protobuf.ByteString getFrameData();

      /**
       * <code>optional int64 frameIndex = 3;</code>
       */
      long getFrameIndex();
    }
    /**
     * Protobuf type {@code VideoSequenceFileRecord.VideoData}
     */
    public  static final class VideoData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:VideoSequenceFileRecord.VideoData)
        VideoDataOrBuilder {
      // Use VideoData.newBuilder() to construct.
      private VideoData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private VideoData() {
        frameNo_ = 0L;
        frameData_ = com.google.protobuf.ByteString.EMPTY;
        frameIndex_ = 0L;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private VideoData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                frameNo_ = input.readInt64();
                break;
              }
              case 18: {

                frameData_ = input.readBytes();
                break;
              }
              case 24: {

                frameIndex_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_VideoData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_VideoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.class, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder.class);
      }

      public static final int FRAMENO_FIELD_NUMBER = 1;
      private long frameNo_;
      /**
       * <code>optional int64 frameNo = 1;</code>
       */
      public long getFrameNo() {
        return frameNo_;
      }

      public static final int FRAMEDATA_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString frameData_;
      /**
       * <code>optional bytes frameData = 2;</code>
       */
      public com.google.protobuf.ByteString getFrameData() {
        return frameData_;
      }

      public static final int FRAMEINDEX_FIELD_NUMBER = 3;
      private long frameIndex_;
      /**
       * <code>optional int64 frameIndex = 3;</code>
       */
      public long getFrameIndex() {
        return frameIndex_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (frameNo_ != 0L) {
          output.writeInt64(1, frameNo_);
        }
        if (!frameData_.isEmpty()) {
          output.writeBytes(2, frameData_);
        }
        if (frameIndex_ != 0L) {
          output.writeInt64(3, frameIndex_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (frameNo_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, frameNo_);
        }
        if (!frameData_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, frameData_);
        }
        if (frameIndex_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, frameIndex_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData)) {
          return super.equals(obj);
        }
        com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData other = (com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData) obj;

        boolean result = true;
        result = result && (getFrameNo()
            == other.getFrameNo());
        result = result && getFrameData()
            .equals(other.getFrameData());
        result = result && (getFrameIndex()
            == other.getFrameIndex());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + FRAMENO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFrameNo());
        hash = (37 * hash) + FRAMEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getFrameData().hashCode();
        hash = (37 * hash) + FRAMEINDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFrameIndex());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code VideoSequenceFileRecord.VideoData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:VideoSequenceFileRecord.VideoData)
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_VideoData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_VideoData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.class, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder.class);
        }

        // Construct using com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          frameNo_ = 0L;

          frameData_ = com.google.protobuf.ByteString.EMPTY;

          frameIndex_ = 0L;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_VideoData_descriptor;
        }

        public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData getDefaultInstanceForType() {
          return com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.getDefaultInstance();
        }

        public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData build() {
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData buildPartial() {
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData result = new com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData(this);
          result.frameNo_ = frameNo_;
          result.frameData_ = frameData_;
          result.frameIndex_ = frameIndex_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData) {
            return mergeFrom((com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData other) {
          if (other == com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.getDefaultInstance()) return this;
          if (other.getFrameNo() != 0L) {
            setFrameNo(other.getFrameNo());
          }
          if (other.getFrameData() != com.google.protobuf.ByteString.EMPTY) {
            setFrameData(other.getFrameData());
          }
          if (other.getFrameIndex() != 0L) {
            setFrameIndex(other.getFrameIndex());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long frameNo_ ;
        /**
         * <code>optional int64 frameNo = 1;</code>
         */
        public long getFrameNo() {
          return frameNo_;
        }
        /**
         * <code>optional int64 frameNo = 1;</code>
         */
        public Builder setFrameNo(long value) {
          
          frameNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 frameNo = 1;</code>
         */
        public Builder clearFrameNo() {
          
          frameNo_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString frameData_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes frameData = 2;</code>
         */
        public com.google.protobuf.ByteString getFrameData() {
          return frameData_;
        }
        /**
         * <code>optional bytes frameData = 2;</code>
         */
        public Builder setFrameData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          frameData_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes frameData = 2;</code>
         */
        public Builder clearFrameData() {
          
          frameData_ = getDefaultInstance().getFrameData();
          onChanged();
          return this;
        }

        private long frameIndex_ ;
        /**
         * <code>optional int64 frameIndex = 3;</code>
         */
        public long getFrameIndex() {
          return frameIndex_;
        }
        /**
         * <code>optional int64 frameIndex = 3;</code>
         */
        public Builder setFrameIndex(long value) {
          
          frameIndex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 frameIndex = 3;</code>
         */
        public Builder clearFrameIndex() {
          
          frameIndex_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:VideoSequenceFileRecord.VideoData)
      }

      // @@protoc_insertion_point(class_scope:VideoSequenceFileRecord.VideoData)
      private static final com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData();
      }

      public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<VideoData>
          PARSER = new com.google.protobuf.AbstractParser<VideoData>() {
        public VideoData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new VideoData(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<VideoData> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<VideoData> getParserForType() {
        return PARSER;
      }

      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int START_FRAME_FIELD_NUMBER = 1;
    private long startFrame_;
    /**
     * <code>optional int64 start_frame = 1;</code>
     */
    public long getStartFrame() {
      return startFrame_;
    }

    public static final int START_INDEX_FIELD_NUMBER = 2;
    private long startIndex_;
    /**
     * <code>optional int64 start_index = 2;</code>
     */
    public long getStartIndex() {
      return startIndex_;
    }

    public static final int END_FRAME_FIELD_NUMBER = 3;
    private long endFrame_;
    /**
     * <code>optional int64 end_frame = 3;</code>
     */
    public long getEndFrame() {
      return endFrame_;
    }

    public static final int END_INDEX_FIELD_NUMBER = 4;
    private long endIndex_;
    /**
     * <code>optional int64 end_index = 4;</code>
     */
    public long getEndIndex() {
      return endIndex_;
    }

    public static final int RECORD_FRAME_NUMBER_FIELD_NUMBER = 5;
    private long recordFrameNumber_;
    /**
     * <code>optional int64 record_frame_number = 5;</code>
     */
    public long getRecordFrameNumber() {
      return recordFrameNumber_;
    }

    public static final int RECORD_VIDEO_DATA_FIELD_NUMBER = 6;
    private java.util.List<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData> recordVideoData_;
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    public java.util.List<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData> getRecordVideoDataList() {
      return recordVideoData_;
    }
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    public java.util.List<? extends com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder> 
        getRecordVideoDataOrBuilderList() {
      return recordVideoData_;
    }
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    public int getRecordVideoDataCount() {
      return recordVideoData_.size();
    }
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData getRecordVideoData(int index) {
      return recordVideoData_.get(index);
    }
    /**
     * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
     */
    public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder getRecordVideoDataOrBuilder(
        int index) {
      return recordVideoData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startFrame_ != 0L) {
        output.writeInt64(1, startFrame_);
      }
      if (startIndex_ != 0L) {
        output.writeInt64(2, startIndex_);
      }
      if (endFrame_ != 0L) {
        output.writeInt64(3, endFrame_);
      }
      if (endIndex_ != 0L) {
        output.writeInt64(4, endIndex_);
      }
      if (recordFrameNumber_ != 0L) {
        output.writeInt64(5, recordFrameNumber_);
      }
      for (int i = 0; i < recordVideoData_.size(); i++) {
        output.writeMessage(6, recordVideoData_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startFrame_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, startFrame_);
      }
      if (startIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startIndex_);
      }
      if (endFrame_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endFrame_);
      }
      if (endIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, endIndex_);
      }
      if (recordFrameNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, recordFrameNumber_);
      }
      for (int i = 0; i < recordVideoData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, recordVideoData_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord)) {
        return super.equals(obj);
      }
      com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord other = (com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord) obj;

      boolean result = true;
      result = result && (getStartFrame()
          == other.getStartFrame());
      result = result && (getStartIndex()
          == other.getStartIndex());
      result = result && (getEndFrame()
          == other.getEndFrame());
      result = result && (getEndIndex()
          == other.getEndIndex());
      result = result && (getRecordFrameNumber()
          == other.getRecordFrameNumber());
      result = result && getRecordVideoDataList()
          .equals(other.getRecordVideoDataList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + START_FRAME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartFrame());
      hash = (37 * hash) + START_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartIndex());
      hash = (37 * hash) + END_FRAME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndFrame());
      hash = (37 * hash) + END_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndIndex());
      hash = (37 * hash) + RECORD_FRAME_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRecordFrameNumber());
      if (getRecordVideoDataCount() > 0) {
        hash = (37 * hash) + RECORD_VIDEO_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getRecordVideoDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VideoSequenceFileRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VideoSequenceFileRecord)
        com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.class, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.Builder.class);
      }

      // Construct using com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordVideoDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        startFrame_ = 0L;

        startIndex_ = 0L;

        endFrame_ = 0L;

        endIndex_ = 0L;

        recordFrameNumber_ = 0L;

        if (recordVideoDataBuilder_ == null) {
          recordVideoData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          recordVideoDataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.Proto.VideoSequenceFileRecordClass.internal_static_VideoSequenceFileRecord_descriptor;
      }

      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord getDefaultInstanceForType() {
        return com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.getDefaultInstance();
      }

      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord build() {
        com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord buildPartial() {
        com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord result = new com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.startFrame_ = startFrame_;
        result.startIndex_ = startIndex_;
        result.endFrame_ = endFrame_;
        result.endIndex_ = endIndex_;
        result.recordFrameNumber_ = recordFrameNumber_;
        if (recordVideoDataBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            recordVideoData_ = java.util.Collections.unmodifiableList(recordVideoData_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.recordVideoData_ = recordVideoData_;
        } else {
          result.recordVideoData_ = recordVideoDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord) {
          return mergeFrom((com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord other) {
        if (other == com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.getDefaultInstance()) return this;
        if (other.getStartFrame() != 0L) {
          setStartFrame(other.getStartFrame());
        }
        if (other.getStartIndex() != 0L) {
          setStartIndex(other.getStartIndex());
        }
        if (other.getEndFrame() != 0L) {
          setEndFrame(other.getEndFrame());
        }
        if (other.getEndIndex() != 0L) {
          setEndIndex(other.getEndIndex());
        }
        if (other.getRecordFrameNumber() != 0L) {
          setRecordFrameNumber(other.getRecordFrameNumber());
        }
        if (recordVideoDataBuilder_ == null) {
          if (!other.recordVideoData_.isEmpty()) {
            if (recordVideoData_.isEmpty()) {
              recordVideoData_ = other.recordVideoData_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureRecordVideoDataIsMutable();
              recordVideoData_.addAll(other.recordVideoData_);
            }
            onChanged();
          }
        } else {
          if (!other.recordVideoData_.isEmpty()) {
            if (recordVideoDataBuilder_.isEmpty()) {
              recordVideoDataBuilder_.dispose();
              recordVideoDataBuilder_ = null;
              recordVideoData_ = other.recordVideoData_;
              bitField0_ = (bitField0_ & ~0x00000020);
              recordVideoDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordVideoDataFieldBuilder() : null;
            } else {
              recordVideoDataBuilder_.addAllMessages(other.recordVideoData_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startFrame_ ;
      /**
       * <code>optional int64 start_frame = 1;</code>
       */
      public long getStartFrame() {
        return startFrame_;
      }
      /**
       * <code>optional int64 start_frame = 1;</code>
       */
      public Builder setStartFrame(long value) {
        
        startFrame_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_frame = 1;</code>
       */
      public Builder clearStartFrame() {
        
        startFrame_ = 0L;
        onChanged();
        return this;
      }

      private long startIndex_ ;
      /**
       * <code>optional int64 start_index = 2;</code>
       */
      public long getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional int64 start_index = 2;</code>
       */
      public Builder setStartIndex(long value) {
        
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_index = 2;</code>
       */
      public Builder clearStartIndex() {
        
        startIndex_ = 0L;
        onChanged();
        return this;
      }

      private long endFrame_ ;
      /**
       * <code>optional int64 end_frame = 3;</code>
       */
      public long getEndFrame() {
        return endFrame_;
      }
      /**
       * <code>optional int64 end_frame = 3;</code>
       */
      public Builder setEndFrame(long value) {
        
        endFrame_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 end_frame = 3;</code>
       */
      public Builder clearEndFrame() {
        
        endFrame_ = 0L;
        onChanged();
        return this;
      }

      private long endIndex_ ;
      /**
       * <code>optional int64 end_index = 4;</code>
       */
      public long getEndIndex() {
        return endIndex_;
      }
      /**
       * <code>optional int64 end_index = 4;</code>
       */
      public Builder setEndIndex(long value) {
        
        endIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 end_index = 4;</code>
       */
      public Builder clearEndIndex() {
        
        endIndex_ = 0L;
        onChanged();
        return this;
      }

      private long recordFrameNumber_ ;
      /**
       * <code>optional int64 record_frame_number = 5;</code>
       */
      public long getRecordFrameNumber() {
        return recordFrameNumber_;
      }
      /**
       * <code>optional int64 record_frame_number = 5;</code>
       */
      public Builder setRecordFrameNumber(long value) {
        
        recordFrameNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 record_frame_number = 5;</code>
       */
      public Builder clearRecordFrameNumber() {
        
        recordFrameNumber_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData> recordVideoData_ =
        java.util.Collections.emptyList();
      private void ensureRecordVideoDataIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          recordVideoData_ = new java.util.ArrayList<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData>(recordVideoData_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder> recordVideoDataBuilder_;

      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public java.util.List<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData> getRecordVideoDataList() {
        if (recordVideoDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recordVideoData_);
        } else {
          return recordVideoDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public int getRecordVideoDataCount() {
        if (recordVideoDataBuilder_ == null) {
          return recordVideoData_.size();
        } else {
          return recordVideoDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData getRecordVideoData(int index) {
        if (recordVideoDataBuilder_ == null) {
          return recordVideoData_.get(index);
        } else {
          return recordVideoDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder setRecordVideoData(
          int index, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData value) {
        if (recordVideoDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordVideoDataIsMutable();
          recordVideoData_.set(index, value);
          onChanged();
        } else {
          recordVideoDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder setRecordVideoData(
          int index, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder builderForValue) {
        if (recordVideoDataBuilder_ == null) {
          ensureRecordVideoDataIsMutable();
          recordVideoData_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordVideoDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder addRecordVideoData(com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData value) {
        if (recordVideoDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordVideoDataIsMutable();
          recordVideoData_.add(value);
          onChanged();
        } else {
          recordVideoDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder addRecordVideoData(
          int index, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData value) {
        if (recordVideoDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordVideoDataIsMutable();
          recordVideoData_.add(index, value);
          onChanged();
        } else {
          recordVideoDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder addRecordVideoData(
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder builderForValue) {
        if (recordVideoDataBuilder_ == null) {
          ensureRecordVideoDataIsMutable();
          recordVideoData_.add(builderForValue.build());
          onChanged();
        } else {
          recordVideoDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder addRecordVideoData(
          int index, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder builderForValue) {
        if (recordVideoDataBuilder_ == null) {
          ensureRecordVideoDataIsMutable();
          recordVideoData_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordVideoDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder addAllRecordVideoData(
          java.lang.Iterable<? extends com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData> values) {
        if (recordVideoDataBuilder_ == null) {
          ensureRecordVideoDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recordVideoData_);
          onChanged();
        } else {
          recordVideoDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder clearRecordVideoData() {
        if (recordVideoDataBuilder_ == null) {
          recordVideoData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          recordVideoDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public Builder removeRecordVideoData(int index) {
        if (recordVideoDataBuilder_ == null) {
          ensureRecordVideoDataIsMutable();
          recordVideoData_.remove(index);
          onChanged();
        } else {
          recordVideoDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder getRecordVideoDataBuilder(
          int index) {
        return getRecordVideoDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder getRecordVideoDataOrBuilder(
          int index) {
        if (recordVideoDataBuilder_ == null) {
          return recordVideoData_.get(index);  } else {
          return recordVideoDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public java.util.List<? extends com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder> 
           getRecordVideoDataOrBuilderList() {
        if (recordVideoDataBuilder_ != null) {
          return recordVideoDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recordVideoData_);
        }
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder addRecordVideoDataBuilder() {
        return getRecordVideoDataFieldBuilder().addBuilder(
            com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.getDefaultInstance());
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder addRecordVideoDataBuilder(
          int index) {
        return getRecordVideoDataFieldBuilder().addBuilder(
            index, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.getDefaultInstance());
      }
      /**
       * <code>repeated .VideoSequenceFileRecord.VideoData record_video_data = 6;</code>
       */
      public java.util.List<com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder> 
           getRecordVideoDataBuilderList() {
        return getRecordVideoDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder> 
          getRecordVideoDataFieldBuilder() {
        if (recordVideoDataBuilder_ == null) {
          recordVideoDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoData.Builder, com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord.VideoDataOrBuilder>(
                  recordVideoData_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          recordVideoData_ = null;
        }
        return recordVideoDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VideoSequenceFileRecord)
    }

    // @@protoc_insertion_point(class_scope:VideoSequenceFileRecord)
    private static final com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord();
    }

    public static com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoSequenceFileRecord>
        PARSER = new com.google.protobuf.AbstractParser<VideoSequenceFileRecord>() {
      public VideoSequenceFileRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VideoSequenceFileRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VideoSequenceFileRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoSequenceFileRecord> getParserForType() {
      return PARSER;
    }

    public com.Proto.VideoSequenceFileRecordClass.VideoSequenceFileRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoSequenceFileRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoSequenceFileRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoSequenceFileRecord_VideoData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoSequenceFileRecord_VideoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031video_sequence_file.proto\"\212\002\n\027VideoSeq" +
      "uenceFileRecord\022\023\n\013start_frame\030\001 \001(\003\022\023\n\013" +
      "start_index\030\002 \001(\003\022\021\n\tend_frame\030\003 \001(\003\022\021\n\t" +
      "end_index\030\004 \001(\003\022\033\n\023record_frame_number\030\005" +
      " \001(\003\022=\n\021record_video_data\030\006 \003(\0132\".VideoS" +
      "equenceFileRecord.VideoData\032C\n\tVideoData" +
      "\022\017\n\007frameNo\030\001 \001(\003\022\021\n\tframeData\030\002 \001(\014\022\022\n\n" +
      "frameIndex\030\003 \001(\003B)\n\tcom.ProtoB\034VideoSequ" +
      "enceFileRecordClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VideoSequenceFileRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VideoSequenceFileRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoSequenceFileRecord_descriptor,
        new java.lang.String[] { "StartFrame", "StartIndex", "EndFrame", "EndIndex", "RecordFrameNumber", "RecordVideoData", });
    internal_static_VideoSequenceFileRecord_VideoData_descriptor =
      internal_static_VideoSequenceFileRecord_descriptor.getNestedTypes().get(0);
    internal_static_VideoSequenceFileRecord_VideoData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoSequenceFileRecord_VideoData_descriptor,
        new java.lang.String[] { "FrameNo", "FrameData", "FrameIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
